version: '3.7'
services:
  updated:
    build: .
    image: qmcgaw/updated
    container_name: updated
    network_mode: bridge
    environment:
      - OUTPUT_DIR=./files
      - PERIOD=24h
      - RESOLVE_HOSTNAMES=no
      - HTTP_TIMEOUT=5s
      - LOG_ENCODING=console
      - LOG_LEVEL=info
      - NAMED_ROOT_MD5=ef14b29649fd3976c6f8e5812b263480
      - ROOT_ANCHORS_SHA256=45336725f9126db810a59896ae93819de743c416262f79c4444042c92e520770
      - TZ=America/Montreal
      - GIT=no
      - GIT_URL=
      - SSH_KEY=./key
      - SSH_KEY_PASSPHRASE=
      - SSH_KNOWN_HOSTS=./known_hosts
      - GOTIFY_URL=
      - GOTIFY_TOKEN=
      - NODE_ID=0
    volumes:
      - ./key:/key:ro
      - ./passphrase:/passphrase:ro
      - ./known_hosts:/known_hosts:ro
      - ./files:/files
    restart: always
