version: '3.7'
services:
  updated:
    build: .
    image: qmcgaw/updated
    container_name: updated
    network_mode: bridge
    environment:
      - OUTPUT_DIR=./files
      - PERIOD=600
      - RESOLVE_HOSTNAMES=no
      - HTTP_TIMEOUT=3000
      - LOG_ENCODING=json
      - LOG_LEVEL=info
      - TZ=America/Montreal
      - GIT=no
      - GIT_URL=
      - SSH_KEY=./key
      - SSH_KEY_PASSPHRASE=
      - SSH_KNOWN_HOSTS=./known_hosts
      - GOTIFY_URL=
      - GOTIFY_TOKEN=
      - NODE_ID=0
    volumes:
      - ./key:/key:ro
      - ./passphrase:/passphrase:ro
      - ./known_hosts:/known_hosts:ro
      - ./files:/files
    restart: always
