version: "3.7"

services:
  vscode:
    image: qmcgaw/godevcontainer
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Montreal
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: -c "while sleep 1000; do :; done"
